---
- name: Desactivar modo kiosko Firefox
  hosts: all
  become: true
  gather_facts: false

  vars:
    kiosk_user: kioskuser
    autostart_file: "/home/kioskuser/.config/autostart/firefox-kiosk.desktop"
    xmodmap_file: "/home/kioskuser/.Xmodmap"

  tasks:

    # --------------------------------------
    # Cerrar Firefox si está ejecutándose
    # --------------------------------------
    - name: Cerrar Firefox del usuario kiosk
      ansible.builtin.shell: |
        pkill -u {{ kiosk_user }} firefox || true

    # --------------------------------------
    # Restaurar teclado (eliminar xmodmap)
    # --------------------------------------
    - name: Restaurar mapa de teclado
      ansible.builtin.shell: |
        xmodmap -e "clear all"
      become_user: "{{ kiosk_user }}"
      ignore_errors: true

    # --------------------------------------
    # Eliminar archivo Xmodmap
    # --------------------------------------
    - name: Eliminar archivo Xmodmap
      ansible.builtin.file:
        path: "{{ xmodmap_file }}"
        state: absent

    # --------------------------------------
    # Eliminar autostart del kiosko
    # --------------------------------------
    - name: Eliminar autostart Firefox Kiosk
      ansible.builtin.file:
        path: "{{ autostart_file }}"
        state: absent

    # --------------------------------------
    # Mensaje final
    # --------------------------------------
    - name: Aviso final
      ansible.builtin.debug:
        msg: "Modo kiosko desactivado. Reinicia el sistema para aplicar los cambios."
