---
- name: Desactivar modo kiosko Firefox (seguro y completo)
  hosts: all
  become: true
  gather_facts: false

  vars:
    kiosk_user: kioskuser
    autostart_file: "/home/{{ kiosk_user }}/.config/autostart/firefox-kiosk.desktop"
    xmodmap_file: "/home/{{ kiosk_user }}/.Xmodmap"
    kiosk_script: "/home/{{ kiosk_user }}/kiosk.sh"

  tasks:

    # --------------------------------------
    # Cerrar Firefox si está ejecutándose
    # --------------------------------------
    - name: Cerrar Firefox del usuario kiosk
      ansible.builtin.shell: |
        pkill -u {{ kiosk_user }} firefox || true

    # --------------------------------------
    # Eliminar bloqueo de teclas (se restaura tras reinicio)
    # --------------------------------------
    - name: Eliminar archivo Xmodmap
      ansible.builtin.file:
        path: "{{ xmodmap_file }}"
        state: absent

    # --------------------------------------
    # Eliminar script de kiosko
    # --------------------------------------
    - name: Eliminar script kiosk.sh
      ansible.builtin.file:
        path: "{{ kiosk_script }}"
        state: absent

    # --------------------------------------
    # Eliminar autostart del kiosko
    # --------------------------------------
    - name: Eliminar autostart Firefox Kiosk
      ansible.builtin.file:
        path: "{{ autostart_file }}"
        state: absent

    # --------------------------------------
    # Mensaje final
    # --------------------------------------
    - name: Aviso final
      ansible.builtin.debug:
        msg: >
          Modo kiosko y bloqueo de teclas desactivados.
          Reinicia el sistema para restaurar completamente el teclado y el escritorio.
