---
- name: Firefox Kiosk definitivo para Linux Mint 21.3 (con bloqueo de teclas)
  hosts: all
  become: true
  gather_facts: true

  vars:
    kiosk_user: kioskuser
    kiosk_url: "https://isard.politecnicllevant.cat/login"

  tasks:

    # --------------------------------------------------
    # Usuario kiosk
    # --------------------------------------------------
    - name: Crear usuario kioskuser
      ansible.builtin.user:
        name: "{{ kiosk_user }}"
        create_home: yes
        shell: /bin/bash
        state: present

    # --------------------------------------------------
    # Firefox
    # --------------------------------------------------
    - name: Instalar Firefox
      ansible.builtin.package:
        name: firefox
        state: present

    # --------------------------------------------------
    # Login automático LightDM (Linux Mint)
    # --------------------------------------------------
    - name: Crear directorio LightDM
      ansible.builtin.file:
        path: /etc/lightdm/lightdm.conf.d
        state: directory
        mode: '0755'

    - name: Configurar login automático para kioskuser
      ansible.builtin.copy:
        dest: /etc/lightdm/lightdm.conf.d/50-autologin.conf
        content: |
          [Seat:*]
          autologin-user={{ kiosk_user }}
          autologin-user-timeout=0
        mode: '0644'

    # --------------------------------------------------
    # Archivo Xmodmap (bloqueo de teclas)
    # --------------------------------------------------
    - name: Crear archivo Xmodmap para bloqueo de teclas
      ansible.builtin.copy:
        dest: /home/{{ kiosk_user }}/.Xmodmap
        content: |
          ! Bloquear Alt
          keycode 64 =
          keycode 108 =

          ! Bloquear Super / Windows
          keycode 133 =
          keycode 134 =

          ! Bloquear Ctrl
          keycode 37 =
          keycode 105 =

          ! Bloquear Escape
          keycode 9 =
        owner: "{{ kiosk_user }}"
        group: "{{ kiosk_user }}"
        mode: '0644'

    # --------------------------------------------------
    # Script KIOSK (FIABLE + bloqueo teclas)
    # --------------------------------------------------
    - name: Crear script de kiosko Firefox
      ansible.builtin.copy:
        dest: /home/{{ kiosk_user }}/kiosk.sh
        content: |
          #!/bin/bash

          export DISPLAY=:0
          export XAUTHORITY=/home/{{ kiosk_user }}/.Xauthority

          # Esperar a que X esté listo
          while ! xdpyinfo -display :0 >/dev/null 2>&1; do
              sleep 1
          done

          # Aplicar bloqueo de teclas
          if [ -f /home/{{ kiosk_user }}/.Xmodmap ]; then
              xmodmap /home/{{ kiosk_user }}/.Xmodmap
          fi

          firefox --kiosk "{{ kiosk_url }}"
        owner: "{{ kiosk_user }}"
        group: "{{ kiosk_user }}"
        mode: '0755'

    # --------------------------------------------------
    # AUTOSTART Cinnamon (CLAVE)
    # --------------------------------------------------
    - name: Crear directorio autostart
      ansible.builtin.file:
        path: /home/{{ kiosk_user }}/.config/autostart
        state: directory
        owner: "{{ kiosk_user }}"
        group: "{{ kiosk_user }}"
        mode: '0755'

    - name: Crear autostart Firefox Kiosk
      ansible.builtin.copy:
        dest: /home/{{ kiosk_user }}/.config/autostart/firefox-kiosk.desktop
        content: |
          [Desktop Entry]
          Type=Application
          Name=Firefox Kiosk
          Exec=/home/{{ kiosk_user }}/kiosk.sh
          X-GNOME-Autostart-enabled=true
        owner: "{{ kiosk_user }}"
        group: "{{ kiosk_user }}"
        mode: '0644'
