---
- name: Configurar Google Chrome en modo Kiosk
  hosts: all
  become: true
  gather_facts: true

  vars:
    kiosk_user: kioskuser
    kiosk_url: "https://isard.politecnicllevant.cat/login"
    display: ":0"
    chrome_path: "/usr/bin/google-chrome"

  tasks:

    - name: Crear usuario para Kiosk si no existe
      ansible.builtin.user:
        name: "{{ kiosk_user }}"
        state: present
        create_home: yes

    - name: Instalar dependencias necesarias para Chrome
      ansible.builtin.package:
        name:
          - libnss3
          - libxss1
          - fonts-liberation
          - wget
          - x11-xserver-utils  # Para xhost
        state: present

    - name: Instalar Google Chrome si no está instalado
      ansible.builtin.shell: |
        if ! command -v google-chrome >/dev/null 2>&1; then
          wget -q -O /tmp/google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          dpkg -i /tmp/google-chrome.deb || apt-get -f install -y
        fi

    - name: Permitir al usuario del kiosk acceder al display
      ansible.builtin.shell: "xhost +SI:localuser:{{ kiosk_user }}"
      environment:
        DISPLAY: "{{ display }}"

    - name: Crear el archivo del servicio systemd para Chrome Kiosk
      ansible.builtin.copy:
        dest: /etc/systemd/system/kiosk.service
        content: |
          [Unit]
          Description=Google Chrome Kiosk
          After=network.target display-manager.service

          [Service]
          User={{ kiosk_user }}
          Environment=DISPLAY={{ display }}
          ExecStart={{ chrome_path }} \
            --kiosk \
            --no-sandbox \
            --disable-gpu \
            --disable-software-rasterizer \
            --incognito \
            {{ kiosk_url }}
          Restart=always
          TimeoutStartSec=300

          [Install]
          WantedBy=multi-user.target
      notify:
        - Recargar systemd

    - name: Habilitar y arrancar el servicio kiosk
      ansible.builtin.systemd:
        name: kiosk.service
        enabled: true
        state: restarted

  handlers:
    - name: Recargar systemd
      ansible.builtin.command: systemctl daemon-reload
