---
- name: Configurar Google Chrome en modo Kiosk (pantalla física)
  hosts: all
  become: true
  gather_facts: true

  vars:
    kiosk_user: kioskuser
    kiosk_url: "https://isard.politecnicllevant.cat/login"
    display: ":0"
    chrome_path: "/usr/bin/google-chrome"
    chrome_flags: "--kiosk --no-sandbox --disable-gpu --disable-software-rasterizer --incognito"

  tasks:

    - name: Crear usuario para Kiosk si no existe
      ansible.builtin.user:
        name: "{{ kiosk_user }}"
        state: present
        create_home: yes
        shell: /bin/bash

    - name: Instalar dependencias necesarias para Chrome
      ansible.builtin.package:
        name:
          - libnss3
          - libxss1
          - fonts-liberation
          - wget
          - x11-xserver-utils
          - apt-transport-https
          - ca-certificates
        state: present

    - name: Instalar Google Chrome si no está instalado
      ansible.builtin.shell: |
        wget -q -O /tmp/google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        dpkg -i /tmp/google-chrome.deb || apt-get -f install -y
      args:
        creates: /usr/bin/google-chrome

    - name: Permitir que el usuario kiosk acceda al display físico
      ansible.builtin.shell: "xhost +SI:localuser:{{ kiosk_user }}"
      environment:
        DISPLAY: "{{ display }}"
      ignore_errors: yes  # No fallar si se ejecuta remotamente y falla

    - name: Crear script de arranque de Chrome Kiosk
      ansible.builtin.copy:
        dest: /home/{{ kiosk_user }}/start-kiosk.sh
        content: |
          #!/bin/bash
          export DISPLAY={{ display }}

          # Ejecutar Chrome en modo kiosk
          exec {{ chrome_path }} {{ chrome_flags }} {{ kiosk_url }}
        owner: "{{ kiosk_user }}"
        group: "{{ kiosk_user }}"
        mode: '0755'

    - name: Crear servicio systemd para Chrome Kiosk
      ansible.builtin.copy:
        dest: /etc/systemd/system/kiosk.service
        content: |
          [Unit]
          Description=Google Chrome Kiosk (Pantalla física)
          After=graphical.target

          [Service]
          User={{ kiosk_user }}
          Environment=DISPLAY={{ display }}
          WorkingDirectory=/home/{{ kiosk_user }}
          ExecStart=/home/{{ kiosk_user }}/start-kiosk.sh
          Restart=always
          TimeoutStartSec=300
          StandardOutput=null
          StandardError=null

          [Install]
          WantedBy=graphical.target
      notify:
        - Recargar systemd

    - name: Habilitar y arrancar el servicio kiosk
      ansible.builtin.systemd:
        name: kiosk.service
        enabled: true
        state: restarted

  handlers:
    - name: Recargar systemd
      ansible.builtin.systemd:
        daemon_reload: yes
