---
- name: Configurar Google Chrome en modo Kiosk (headless con Xvfb)
  hosts: all
  become: true
  gather_facts: true

  vars:
    kiosk_user: kioskuser
    kiosk_url: "https://isard.politecnicllevant.cat/login"
    display: ":99"
    chrome_path: "/usr/bin/google-chrome"
    chrome_flags: "--kiosk --no-sandbox --disable-gpu --disable-software-rasterizer --incognito"

  tasks:

    - name: Crear usuario para Kiosk si no existe
      ansible.builtin.user:
        name: "{{ kiosk_user }}"
        state: present
        create_home: yes
        shell: /bin/bash

    - name: Instalar dependencias necesarias para Chrome y Xvfb
      ansible.builtin.package:
        name:
          - libnss3
          - libxss1
          - fonts-liberation
          - wget
          - xvfb
          - x11-xserver-utils
          - apt-transport-https
          - ca-certificates
        state: present

    - name: Instalar Google Chrome si no está instalado
      ansible.builtin.shell: |
        wget -q -O /tmp/google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        dpkg -i /tmp/google-chrome.deb || apt-get -f install -y
      args:
        creates: /usr/bin/google-chrome

    - name: Crear servicio systemd para Chrome Kiosk con Xvfb
      ansible.builtin.copy:
        dest: /etc/systemd/system/kiosk.service
        content: |
          [Unit]
          Description=Google Chrome Kiosk (headless Xvfb)
          After=network.target

          [Service]
          User={{ kiosk_user }}
          Environment=DISPLAY={{ display }}
          WorkingDirectory=/home/{{ kiosk_user }}
          ExecStart=/usr/bin/Xvfb {{ display }} -screen 0 1920x1080x24 &
                     {{ chrome_path }} {{ chrome_flags }} {{ kiosk_url }}
          Restart=always
          TimeoutStartSec=300
          StandardOutput=null
          StandardError=null

          [Install]
          WantedBy=multi-user.target
      notify:
        - Recargar systemd

    - name: Habilitar y arrancar el servicio kiosk
      ansible.builtin.systemd:
        name: kiosk.service
        enabled: true
        state: restarted

  handlers:
    - name: Recargar systemd
      ansible.builtin.systemd:
        daemon_reload: yes
