---
- name: Configurar Google Chrome en modo Kiosk (pantalla física o Xvfb) con login automático
  hosts: all
  become: true
  gather_facts: true

  vars:
    kiosk_user: kioskuser
    kiosk_url: "https://isard.politecnicllevant.cat/login"
    display_physical: ":0"
    display_virtual: ":99"
    chrome_path: "/usr/bin/google-chrome"
    chrome_flags: "--kiosk --no-sandbox --disable-gpu --disable-software-rasterizer --incognito"

  tasks:

    # -------------------------------
    # Mostrar distribución detectada (para debug)
    # -------------------------------
    - name: Mostrar distribución detectada
      ansible.builtin.debug:
        var: ansible_facts['distribution']

    # -------------------------------
    # Crear usuario Kiosk
    # -------------------------------
    - name: Crear usuario para Kiosk si no existe
      ansible.builtin.user:
        name: "{{ kiosk_user }}"
        state: present
        create_home: yes
        shell: /bin/bash

    # -------------------------------
    # Instalar dependencias y Chrome
    # -------------------------------
    - name: Instalar dependencias necesarias para Chrome y Xvfb
      ansible.builtin.package:
        name:
          - libnss3
          - libxss1
          - fonts-liberation
          - wget
          - xvfb
          - x11-xserver-utils
          - apt-transport-https
          - ca-certificates
        state: present

    - name: Instalar Google Chrome si no está instalado
      ansible.builtin.shell: |
        wget -q -O /tmp/google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        dpkg -i /tmp/google-chrome.deb || apt-get -f install -y
      args:
        creates: /usr/bin/google-chrome

    # -------------------------------
    # Configurar login automático
    # -------------------------------
    - name: Configurar login automático en LightDM
      ansible.builtin.blockinfile:
        path: /etc/lightdm/lightdm.conf
        block: |
          [Seat:*]
          autologin-user={{ kiosk_user }}
          autologin-user-timeout=0
      when: ansible_facts['os_family'] == "Debian"

    - name: Configurar login automático en GDM (GNOME/Ubuntu)
      ansible.builtin.ini_file:
        path: /etc/gdm3/custom.conf
        section: daemon
        option: AutomaticLogin
        value: "{{ kiosk_user }}"
      when: ansible_facts['os_family'] == "Debian"

    - name: Habilitar AutomaticLogin en GDM
      ansible.builtin.ini_file:
        path: /etc/gdm3/custom.conf
        section: daemon
        option: AutomaticLoginEnable
        value: "true"
      when: ansible_facts['os_family'] == "Debian"

    # -------------------------------
    # Detectar si hay Xorg en pantalla física
    # -------------------------------
    - name: Detectar si hay sesión gráfica activa en :0
      ansible.builtin.shell: "pgrep -u {{ kiosk_user }} -f Xorg || true"
      register: xorg_check
      changed_when: false

    - name: Configurar DISPLAY y método de ejecución
      ansible.builtin.set_fact:
        kiosk_display: "{{ display_physical if xorg_check.stdout|length > 0 else display_virtual }}"
        use_xvfb: "{{ True if xorg_check.stdout|length == 0 else False }}"

    # -------------------------------
    # Crear script de arranque
    # -------------------------------
    - name: Crear script de arranque de Chrome Kiosk
      ansible.builtin.copy:
        dest: /home/{{ kiosk_user }}/start-kiosk.sh
        content: |
          #!/bin/bash
          export DISPLAY={{ kiosk_display }}

          {% if use_xvfb %}
          # Iniciar Xvfb si no está corriendo
          if ! pgrep Xvfb > /dev/null; then
              Xvfb $DISPLAY -screen 0 1920x1080x24 &
              sleep 2
          fi
          {% else %}
          # Permitir que el usuario acceda al display físico
          xhost +SI:localuser:{{ kiosk_user }} || true
          {% endif %}

          # Ejecutar Chrome en modo kiosk
          exec {{ chrome_path }} {{ chrome_flags }} {{ kiosk_url }}
        owner: "{{ kiosk_user }}"
        group: "{{ kiosk_user }}"
        mode: '0755'

    # -------------------------------
    # Crear servicio systemd
    # -------------------------------
    - name: Crear servicio systemd para Chrome Kiosk
      ansible.builtin.copy:
        dest: /etc/systemd/system/kiosk.service
        content: |
          [Unit]
          Description=Google Chrome Kiosk (Universal)
          After=network.target

          [Service]
          User={{ kiosk_user }}
          Environment=DISPLAY={{ kiosk_display }}
          WorkingDirectory=/home/{{ kiosk_user }}
          ExecStart=/home/{{ kiosk_user }}/start-kiosk.sh
          Restart=always
          TimeoutStartSec=300
          StandardOutput=journal
          StandardError=journal

          [Install]
          WantedBy=graphical.target
      notify:
        - Recargar systemd

    - name: Habilitar y arrancar el servicio kiosk
      ansible.builtin.systemd:
        name: kiosk.service
        enabled: true
        state: restarted

  handlers:
    - name: Recargar systemd
      ansible.builtin.systemd:
        daemon_reload: yes
